In [2]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

names_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "clas"]
df = pd.read_csv("iris.data", names=names_columns)
df.clas.unique()


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### QUESTÃO 3

In [1]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

# Ler arquivo e Pegar colunas
names_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "Class"]
df = pd.read_csv("iris.data", names=names_columns)

# Especie de PRINT pra vê o arquivo
df.Class.unique()

# Separo as classes pelos tipos de flores
setosa = df[(df['Class'] == 'Iris-setosa')]
versicolor = df[(df['Class'] == 'Iris-versicolor')]
virginica = df[(df['Class'] == 'Iris-virginica')]


# train_test_split: Dividir arrays ou matrizes em subconjuntos aleatórios de treino e teste
# test_size=0.5 (tamanho da divisão, ex: 0.5 representa a metade)

# SETOSA
setosa_x = setosa[setosa.columns[:4:]]
setosa_y = setosa[setosa.columns[-1::]]

setosa_x_treino, setosa_x_teste, setosa_y_treino, setosa_y_teste = train_test_split (setosa_x, setosa_y, test_size=0.5)

# VERSICOLO
versicolor_x = versicolor[versicolor.columns[:4:]]
versicolor_y = versicolor[versicolor.columns[-1::]]

versicolor_x_treino, versicolor_x_teste, versicolor_y_treino, versicolor_y_teste = train_test_split (versicolor_x,versicolor_y,test_size=0.5)

# VIRGINICA
virginica_x = virginica[virginica.columns[:4:]]
virginica_y = virginica[virginica.columns[-1::]]

virginica_x_treino, virginica_x_teste, virginica_y_treino, virginica_y_teste = train_test_split (virginica_x, virginica_y,test_size=0.5)


# Junta os conjuntos de treino e teste pelos grupos
# TREINO
x_treino = pd.concat([setosa_x_treino, versicolor_x_treino, virginica_x_treino])
y_treino = pd.concat([setosa_y_treino, versicolor_y_treino, virginica_y_treino])

# TESTE
x_teste = pd.concat([setosa_x_teste, versicolor_x_teste, virginica_x_teste])
y_teste = pd.concat([setosa_y_teste, versicolor_y_teste, virginica_y_teste])

# Padroniza os recursos removendo a média e dimensionando para a variação da unidade
scaler = StandardScaler()
# Calcula a média e o padrão a serem usados para dimensionamento posterior
# Ajusta aos dados e, em seguida, transforma-os.
scaler.fit(x_treino)
x_treino = scaler.transform(x_treino)
x_teste = scaler.transform(x_teste)

# Classificador que implementa o voto dos k vizinhos mais próximos.
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(x_treino, y_treino)

y_pred = classifier.predict(x_teste)

print(classification_report(y_teste, y_pred))
print(confusion_matrix(y_teste, y_pred))

print("Porcentagem acertos: ", str(format(accuracy_score(y_teste, y_pred)*100, '.2f') + "%"))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        25
Iris-versicolor       0.85      0.92      0.88        25
 Iris-virginica       0.91      0.84      0.87        25

       accuracy                           0.92        75
      macro avg       0.92      0.92      0.92        75
   weighted avg       0.92      0.92      0.92        75

[[25  0  0]
 [ 0 23  2]
 [ 0  4 21]]
Porcentagem acertos:  92.00%


/home/laisy/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


### QUESTÃO 4 

In [3]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

def calc_distancia(treino, teste):
    # distância euclidiana
    distancia = ((treino[0]-teste[0])**2 + (treino[1]-teste[1])**2 + (treino[2]-teste[2])**2 + (treino[3]-teste[3])**2)**0.5
    return distancia

def array_valores(row):
    array = []
    array.append(row["sepal_length"])
    array.append(row["sepal_width"])
    array.append(row["petal_length"])
    array.append(row["petal_width"])
    return array

names_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "Class"]
df = pd.read_csv("iris.data", names=names_columns)
df.Class.unique()

setosa = df[(df['Class'] == 'Iris-setosa')]
versicolor = df[(df['Class'] == 'Iris-versicolor')]
virginica = df[(df['Class'] == 'Iris-virginica')]

# SETOSA
setosa_treino, setosa_teste = train_test_split(setosa,test_size=0.5)

# VERSICOLO
versicolor_treino, versicolor_teste = train_test_split(versicolor,test_size=0.5)

# VIRGINICA
virginica_treino, virginica_teste = train_test_split(virginica,test_size=0.5)

# TREINO
treino = pd.concat([setosa_treino, versicolor_treino, virginica_treino])
x_treino = treino[treino.columns[:4:]]
y_treino = treino[treino.columns[-1::]]

# TESTE
teste = pd.concat([setosa_teste, versicolor_teste, virginica_teste])
x_teste = teste[teste.columns[:4:]]
y_teste = teste[teste.columns[-1::]]

y_pred = y_teste.copy()

# para cada iteração do loop externo: terá as informações da instância atual do conjunto de teste, todas as instâncias do conjunto treino serão percorridas, 
# calculando a distância e substituindo a classe no dataframe de predição caso seja a menor distância

# Métodos do Pandas - iterrows: gera um objeto iterador do DataFrame, permitindo iterar cada linha do DataFrame.
# Cada iteração produz um objeto de índice e um objeto de linha (um objeto da série Pandas).
for k, row1 in x_teste.iterrows():
    array_dist_teste = array_valores(row1)
    # maior tamanho possivel para ir atualizando
    menor_dist = 999999.9
    for j, row2 in x_treino.iterrows():
        array_dist_treino = array_valores(row2)
        distancia = calc_distancia(array_dist_treino, array_dist_teste)
        if (distancia < menor_dist):
            menor_dist = distancia
            y_pred.loc[k, 'Class'] = y_treino.loc[j, 'Class']

print(classification_report(y_teste, y_pred))
print(confusion_matrix(y_teste, y_pred))
print("Porcentagem acertos: ", str(format(accuracy_score(y_teste, y_pred)*100, '.2f') + "%"))

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/laisy/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_51610/3231937612.py", line 52, in <module>
    df.x_teste.iterrows()
  File "/home/laisy/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'x_teste'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laisy/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2052, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/laisy/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/laisy/.local/lib/python3.8/site-packages/I

### Questão 5 - 7-NN com peso

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

names_columns = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

df = pd.read_csv("wine.data", names=names_columns)
df.Alcohol.unique()

classe_1 = df[(df['Class'] == 1)]
classe_2 = df[(df['Class'] == 2)]
classe_3 = df[(df['Class'] == 3)]

classe_1_treino, classe_1_teste = train_test_split(classe_1,test_size=0.5)
classe_2_treino, classe_2_teste = train_test_split(classe_2,test_size=0.5)
classe_3_treino, classe_3_teste = train_test_split(classe_3,test_size=0.5)

# treino
treino = pd.concat([classe_1_treino, classe_2_treino, classe_3_treino])
x_treino = treino[treino.columns[1:13:]]
y_treino = treino[treino.columns[:1:]]

# teste
teste = pd.concat([classe_1_teste, classe_2_teste, classe_3_teste])
x_teste = teste[teste.columns[1:13:]]
y_teste = teste[teste.columns[:1:]]

scaler = StandardScaler()
scaler.fit(x_treino)
x_treino = scaler.transform(x_treino)
x_teste = scaler.transform(x_teste)

# PESO: weights='distance'
classificador = KNeighborsClassifier(n_neighbors=7, weights='distance')
classificador.fit(x_treino, y_treino)

y_pred = classificador.predict(x_teste)

print(classification_report(y_teste, y_pred))
print(confusion_matrix(y_teste, y_pred))
print("Porcentagem acertos: ", str(format(accuracy_score(y_teste, y_pred)*100, '.2f') + "%"))

              precision    recall  f1-score   support

           1       0.88      1.00      0.94        30
           2       1.00      0.78      0.88        36
           3       0.86      1.00      0.92        24

    accuracy                           0.91        90
   macro avg       0.91      0.93      0.91        90
weighted avg       0.92      0.91      0.91        90

[[30  0  0]
 [ 4 28  4]
 [ 0  0 24]]
Porcentagem acertos:  91.11%


/home/laisy/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


### Questão 5 - 7-NN sem peso

In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

names_columns = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

df = pd.read_csv("wine.data", names=names_columns)
df.Alcohol.unique()

classe_1 = df[(df['Class'] == 1)]
classe_2 = df[(df['Class'] == 2)]
classe_3 = df[(df['Class'] == 3)]

classe_1_treino, classe_1_teste = train_test_split(classe_1,test_size=0.5)
classe_2_treino, classe_2_teste = train_test_split(classe_2,test_size=0.5)
classe_3_treino, classe_3_teste = train_test_split(classe_3,test_size=0.5)

# treino
treino = pd.concat([classe_1_treino, classe_2_treino, classe_3_treino])
x_treino = treino[treino.columns[1:13:]]
y_treino = treino[treino.columns[:1:]]

# teste
teste = pd.concat([classe_1_teste, classe_2_teste, classe_3_teste])
x_teste = teste[teste.columns[1:13:]]
y_teste = teste[teste.columns[:1:]]

scaler = StandardScaler()
scaler.fit(x_treino)
x_treino = scaler.transform(x_treino)
x_teste = scaler.transform(x_teste)

# SEM PESO
classificador = KNeighborsClassifier(n_neighbors=7)
classificador.fit(x_treino, y_treino)

y_pred = classificador.predict(x_teste)

print(classification_report(y_teste, y_pred))
print(confusion_matrix(y_teste, y_pred))
print("Porcentagem acertos: ", str(format(accuracy_score(y_teste, y_pred)*100, '.2f') + "%"))

              precision    recall  f1-score   support

           1       0.85      0.93      0.89        30
           2       0.93      0.78      0.85        36
           3       0.89      1.00      0.94        24

    accuracy                           0.89        90
   macro avg       0.89      0.90      0.89        90
weighted avg       0.89      0.89      0.89        90

[[28  2  0]
 [ 5 28  3]
 [ 0  0 24]]
Porcentagem acertos:  88.89%


/home/laisy/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


### DISTANCIA EUCLIDIANA

In [13]:
def calc_distancia(treino, teste):
    # distância euclidiana
    distancia = ((treino[0]-teste[0])**2 + (treino[1]-teste[1])**2 + (treino[2]-teste[2])**2 + (treino[3]-teste[3])**2)**0.5
    return distancia

treino = [5.1, 3.5, 1.4, 0.2]
teste = [6.7, 3.1, 4.4, 1.4]

print(calc_distancia(treino, teste))

#TREINO
#[5.1, 3.5, 1.4, 0.2]
#[4.9, 3.0, 1.4, 0.2]
#[6.9, 3.1, 4.9, 1.5]
#[5.6, 3.0, 4.5, 1.5]
#[6.8, 3.0, 5.5, 2.1]
#[5.8, 2.7, 5.1, 1.9]

#TESTE
#[4.7, 3.2, 1.3, 0.2]
#[7.2, 3.0, 5.8, 1.6]
#[6.7, 3.1, 4.4, 1.4]

4.208325082500163
