Q1 - INCOMPLETA

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

In [ ]:
def saidaNeuronio(w, ex):
    v = 0
    for i in range(len(ex)):
        v = v + w[i] * ex[i]
        if (v > 0):
            return 1
        else:
            return 0
            

In [ ]:
def treinamento(y, x, eta, n, d, w, erroMax):
    erroTotal = erroMax
    epoca = 0
    i = 0
    j = 0
    k = 0
    atualizacao = 0
    # printSuperficieDecisao(300, -1, 2, -1, 2, w, x, y, 10, "Início")
    while(erroTotal >= erroMax):
        epoca += 1
        print("\n Epoca" + epoca)
        while(i < n):
            f = saidaNeuronio(w, x[i])
            delta = y[i] - f
            erro = delta * delta
            erroTotal = erroTotal + erro
            print("y[" + i + "]=" + y[i] + ",f=" + f)
            if(erro > 0):
                atualizacao += 1
                # atualiza os pesos
                while(j < d):
                    w[j] = w[j] + eta + x[i][j] * delta
                    print(",w[" + j + "]=" + w[j])
                    # printSuperficieDecisao(300, -1, 2, -1, 2, w, x, y, 10, "Atualizacao #" + atualizacao)
                    j += 1
            i += 1
        
        # Calcula o erro do neuronio
        erroTotal = 0
        while(k < n):
            f = saidaNeuronio(w, x[i])
            delta = y[i] - f
            erro = delta * delta
            erroTotal = erroTotal + erro
        print("Erro Total = " + erroTotal)


In [26]:
df = pd.read_csv("iris.data", header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [27]:
x = df[df.columns[:-1]].to_numpy()
y = df[df.columns[-1]].to_numpy()

treinoX, testeX, treinoY, testeY = train_test_split(x,y,test_size=0.50, random_state=1)

skf = StratifiedKFold(n_splits=2)

for train, test in skf.split(x, y):
    X_train, X_test = x[train], x[test]
    y_train, y_test = y[train], y[test]



In [28]:
for i in range(len(y)):
    treinoX, testeX, treinoY, testeY = train_test_split(x,y,test_size=0.50)




Q2

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.utils import np_utils
from keras.optimizers import gradient_descent_v2
import pandas as pd
import numpy as np

In [4]:
def mediaAmostral(accuracyArray):
    return np.mean(accuracyArray)

In [5]:
def desvioPadraoAmostral(accuracyArray):
    # ddof: Significa Graus de Liberdade Delta. O divisor usado nos cálculos é N - ddof, onde N representa o número de elementos. Por padrão, ddof é zero.
    return np.std(accuracyArray, ddof = 1)

In [6]:
df = pd.read_csv("wine.data", sep=",", header=None)
# .astype(float) converter uma coluna do tipo string/int para float
x = df[df.columns[1:]].astype(float)
y = df[df.columns[0]]

In [7]:
#   PRÉ-PROCESSAMENTO
#  Codifique rótulos de destino com valor entre 0 e n_classes-1.
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# le = preprocessing.LabelEncoder()
# >>> le.fit([1, 2, 2, 6])
# LabelEncoder()
# >>> le.classes_
# array([1, 2, 6])
# >>> le.transform([1, 1, 2, 6])
# array([0, 0, 1, 2]...)
# >>> le.inverse_transform([0, 0, 1, 2])
# array([1, 1, 2, 6])




In [8]:
# um array numpy (ou) um vetor que possui números inteiros que representam diferentes categorias, 
# pode ser convertido em um array numpy (ou) uma matriz que possui valores binários e possui colunas iguais ao número de categorias no dados.
# Esta função retorna uma matriz de valores binários (‘1’ ou ‘0’). 
# Possui número de linhas igual ao comprimento do vetor de entrada e número de colunas igual ao número de classes.
bin_y = np_utils.to_categorical(encoded_Y)

In [9]:
print(y)
print("\n")

print(encoded_Y)
print("\n")

print(bin_y)

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 

In [11]:
# Um modelo sequencial é apropriado para uma pilha simples de camadas onde cada camada tem exatamente um tensor de entrada e um tensor de saída.

model = Sequential()
# modelo sequencial de forma incremental 
# a especificação de sua forma de entrada por meio do argumento input_dim
# Dense(38) é uma camada totalmente conectada com 38 unidades ocultas.
model.add(Dense(38, input_dim = 13))
# Função de ativação sigmoide  
# Saída ε [0, 1] Derivada em [0; 0,25]
model.add(Activation("sigmoid"))
model.add(Dense(3))
# Softmax é uma função matemática que converte um vetor de números em um vetor de probabilidades, 
# onde as probabilidades de cada valor são proporcionais à escala relativa de cada valor no vetor.
model.add(Activation("softmax"))

In [13]:
accuracyList = []
for i in range(30):
    treinoX,testeX,treinoY,testeY = train_test_split(x,bin_y, train_size=0.5,random_state=i)
    model.compile(optimizer= 'adam',loss= "binary_crossentropy", metrics=["accuracy"])
    model.fit(treinoX, treinoY, epochs=200, verbose= 0)

    loss, accuracy = model.evaluate(testeX,testeY, verbose= 0)

    accuracyList.append(accuracy)
    #print (accuracy)


In [16]:
print("\n")
print("Lista de acertos: " + str(accuracyList))
print("\n")
print("Desvio Padrão acuracia: " + str(desvioPadraoAmostral(accuracyList)))
print("\n")
print("Media da acuracia: " + str(mediaAmostral(accuracyList)))



Lista de acertos: [0.9438202381134033, 1.0, 0.9775280952453613, 0.966292142868042, 0.966292142868042, 0.9438202381134033, 0.9438202381134033, 0.9775280952453613, 0.9550561904907227, 0.9775280952453613, 0.9775280952453613, 0.9438202381134033, 0.9775280952453613, 1.0, 0.9775280952453613, 0.9887640476226807, 0.9887640476226807, 0.966292142868042, 0.9775280952453613, 0.9213483333587646, 0.966292142868042, 0.9887640476226807, 0.966292142868042, 0.9550561904907227, 0.9887640476226807, 0.9550561904907227, 0.966292142868042, 0.9775280952453613, 0.9775280952453613, 0.9775280952453613]


Desvio Padrão acuracia: 0.01822523596221791


Media da acuracia: 0.9696629285812378


Q3 - INCOMPLETA

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [21]:
df = pd.read_csv("spiral.csv")
df

In [29]:
x = df[df.columns[0:-1]]
y = df[df.columns[-1]]

mlp = MLPClassifier(max_iter=35, verbose=True, learning_rate='constant', hidden_layer_sizes=(1,2,3), learning_rate_init=0.3, activation='logistic',)

treinoX, testeX, treinoY, testeY = train_test_split(x,y,test_size=0.50, random_state=1)

mlp.fit(treinoX, treinoY)
saida = mlp.predict(testeX)

mlp.score(testeX, testeY)

Iteration 1, loss = 1.19349639
Iteration 2, loss = 1.20373912
Iteration 3, loss = 1.20195108
Iteration 4, loss = 1.14661321
Iteration 5, loss = 1.10686153
Iteration 6, loss = 1.11330905
Iteration 7, loss = 1.12877919
Iteration 8, loss = 1.13165280
Iteration 9, loss = 1.12488347
Iteration 10, loss = 1.11484448
Iteration 11, loss = 1.10523947
Iteration 12, loss = 1.09955468
Iteration 13, loss = 1.10028309
Iteration 14, loss = 1.10597132
Iteration 15, loss = 1.11138056
Iteration 16, loss = 1.11206644
Iteration 17, loss = 1.10786002
Iteration 18, loss = 1.10194249
Iteration 19, loss = 1.09784171
Iteration 20, loss = 1.09718153
Iteration 21, loss = 1.09924106
Iteration 22, loss = 1.10199298
Iteration 23, loss = 1.10357208
Iteration 24, loss = 1.10320719
Iteration 25, loss = 1.10132151
Iteration 26, loss = 1.09904881
Iteration 27, loss = 1.09753293
Iteration 28, loss = 1.09732833
Iteration 29, loss = 1.09817248
Iteration 30, loss = 1.09925542
Iteration 31, loss = 1.09980137
Training loss did

0.32