Q2

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.utils import np_utils
from keras.optimizers import gradient_descent_v2
import pandas as pd
import numpy as np

In [4]:
def mediaAmostral(accuracyArray):
    return np.mean(accuracyArray)

In [5]:
def desvioPadraoAmostral(accuracyArray):
    # ddof: Significa Graus de Liberdade Delta. O divisor usado nos cálculos é N - ddof, onde N representa o número de elementos. Por padrão, ddof é zero.
    return np.std(accuracyArray, ddof = 1)

In [6]:
df = pd.read_csv("wine.data", sep=",", header=None)
# .astype(float) converter uma coluna do tipo string/int para float
x = df[df.columns[1:]].astype(float)
y = df[df.columns[0]]

In [7]:
#   PRÉ-PROCESSAMENTO
#  Codifique rótulos de destino com valor entre 0 e n_classes-1.
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# le = preprocessing.LabelEncoder()
# >>> le.fit([1, 2, 2, 6])
# LabelEncoder()
# >>> le.classes_
# array([1, 2, 6])
# >>> le.transform([1, 1, 2, 6])
# array([0, 0, 1, 2]...)
# >>> le.inverse_transform([0, 0, 1, 2])
# array([1, 1, 2, 6])




In [8]:
# um array numpy (ou) um vetor que possui números inteiros que representam diferentes categorias, 
# pode ser convertido em um array numpy (ou) uma matriz que possui valores binários e possui colunas iguais ao número de categorias no dados.
# Esta função retorna uma matriz de valores binários (‘1’ ou ‘0’). 
# Possui número de linhas igual ao comprimento do vetor de entrada e número de colunas igual ao número de classes.
bin_y = np_utils.to_categorical(encoded_Y)

In [9]:
print(y)
print("\n")

print(encoded_Y)
print("\n")

print(bin_y)

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 

In [11]:
# Um modelo sequencial é apropriado para uma pilha simples de camadas onde cada camada tem exatamente um tensor de entrada e um tensor de saída.

model = Sequential()
# modelo sequencial de forma incremental 
# a especificação de sua forma de entrada por meio do argumento input_dim
# Dense(38) é uma camada totalmente conectada com 38 unidades ocultas.
model.add(Dense(38, input_dim = 13))
# Função de ativação sigmoide  
# Saída ε [0, 1] Derivada em [0; 0,25]
model.add(Activation("sigmoid"))
model.add(Dense(3))
# Softmax é uma função matemática que converte um vetor de números em um vetor de probabilidades, 
# onde as probabilidades de cada valor são proporcionais à escala relativa de cada valor no vetor.
model.add(Activation("softmax"))

In [13]:
accuracyList = []
for i in range(30):
    treinoX,testeX,treinoY,testeY = train_test_split(x,bin_y, train_size=0.5,random_state=i)
    model.compile(optimizer= 'adam',loss= "binary_crossentropy", metrics=["accuracy"])
    model.fit(treinoX, treinoY, epochs=200, verbose= 0)

    loss, accuracy = model.evaluate(testeX,testeY, verbose= 0)

    accuracyList.append(accuracy)
    #print (accuracy)


In [16]:
print("\n")
print("Lista de acertos: " + str(accuracyList))
print("\n")
print("Desvio Padrão acuracia: " + str(desvioPadraoAmostral(accuracyList)))
print("\n")
print("Media da acuracia: " + str(mediaAmostral(accuracyList)))



Lista de acertos: [0.9438202381134033, 1.0, 0.9775280952453613, 0.966292142868042, 0.966292142868042, 0.9438202381134033, 0.9438202381134033, 0.9775280952453613, 0.9550561904907227, 0.9775280952453613, 0.9775280952453613, 0.9438202381134033, 0.9775280952453613, 1.0, 0.9775280952453613, 0.9887640476226807, 0.9887640476226807, 0.966292142868042, 0.9775280952453613, 0.9213483333587646, 0.966292142868042, 0.9887640476226807, 0.966292142868042, 0.9550561904907227, 0.9887640476226807, 0.9550561904907227, 0.966292142868042, 0.9775280952453613, 0.9775280952453613, 0.9775280952453613]


Desvio Padrão acuracia: 0.01822523596221791


Media da acuracia: 0.9696629285812378
